trigger:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'

steps:
- template: templates/steps/deploy-steps-template.yml
  parameters:
    location: 'westeurope'
    repoURL: 'https://github.com/demitry/eventgrid-viewer-blazor.git'